version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: api_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: api_db
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:

